import React, { useState } from 'react';
import Head from 'next/head'
import Script from 'next/script'
import Contact from '../components/Contact'
import Jumbotron from '../components/Jumbotron'
import ProductList from '../components/ProductList'
import ModalAccessCart from '../components/ModalAccessCart'
import { IProduct } from '../components/Product'
import { GetStaticProps } from 'next'
import iphone from '../public/logo.png'

interface IProductListProps {
  products: IProduct[]
}

export default function Home({ products}: IProductListProps ) {
  const [modalOpened, setModalOpened] = useState(false)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <link rel="preconnect" href="https://app.snipcart.com" />
      <link rel="preconnect" href="https://cdn.snipcart.com" />
      <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css" />


      <main>
        <ModalAccessCart show={modalOpened} onClose={() => setModalOpened(false)}/>
        <Jumbotron />
        <ProductList products={products} onAddProductToCart={() => setModalOpened(true)}/>
        <Contact />
      </main>

      <Script src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js" />
      <div hidden id="snipcart" data-api-key="OWNlZTNlYmItZTU5OS00MmI4LThjOTAtMjY0NzAyYmI2ODAxNjM3NjIyMjY3MDMxMTIzMzUx"></div>
    </div>
  )
}


export const products: IProduct[] = [
  {
    id: "1",
    name: "iphone X",
    price: 300,
    description: "Le meilleur iPhone X de tous",
    url: "/api/products/iphone",
    image: iphone
  }, {
    id: "2",
    name: "iphone XR",
    price: 250,
    description: "Le meilleur iPhone XR de tous",
    url: "/api/products/iphone",
    image: iphone
  }, {
    id: "3",
    name: "iphone XS",
    price: 200,
    description: "Le meilleur iPhone XS de tous",
    url: "/api/products/iphone",
    image: iphone
  }
]

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props:{
      products
    }
  }
}